"""add workers table and job worker foreign key

Revision ID: 522668470244
Revises: c4a9b6681358
Create Date: 2026-09-24 17:04:53.540231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522668470244'
down_revision: Union[str, Sequence[str], None] = 'c4a9b6681358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('last_heartbeat', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('jobs', 'worker_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='worker_id::uuid')
    op.create_foreign_key('fk_jobs_worker_id_workers', 'jobs', 'workers', ['worker_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_worker_id_workers', 'jobs', type_='foreignkey')
    op.alter_column('jobs', 'worker_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='worker_id::text')
    op.drop_table('workers')
    # ### end Alembic commands ###
