"""added worker_id to jobs table

Revision ID: c4a9b6681358
Revises: 8f2c1e7a9b6d
Create Date: 2026-09-24 16:08:55.412140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a9b6681358'
down_revision: Union[str, Sequence[str], None] = '8f2c1e7a9b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('worker_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'worker_id')
    # ### end Alembic commands ###
